name: Hello Pipeline

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Second Job
        run: echo "Job 1 was successful 🎉"
